# scene
scene: igibson
scene_id: Rs_int
load_scene_episode_config: false
scene_episode_config_name: null
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: with_obj
trav_map_resolution: 0.1
trav_map_default_resolution: 0.1
trav_map_erosion: 6
should_open_all_doors: false
not_load_object_categories: [door, carpet]
texture_scale: 0.5

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot: Locobot
is_discrete: false
linear_velocity: 0.5
angular_velocity: 1.5707963267948966

# task
task: social_nav_random
target_dist_min: 1.0
target_dist_max: 10.0
goal_format: polar
task_obs_dim: 4
waypoint_resolution: 0.1
orca_radius: 0.5
pedestrian_collision_threshold: 0.3

# reward
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.0

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# sensor spec
output: [task_obs, rgb, depth]
# image
# Intel Realsense Depth Camera D435
# https://store.intelrealsense.com/buy-intel-realsense-depth-camera-d435.html
fisheye: false
image_width: 320
image_height: 180
vertical_fov: 42.5
# depth
depth_low : 0.1
depth_high: 10.0

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false
