# igibson simulator

n_robot: 2
robot_ns: "jackalJaco"

### NUA TODO: DEPRECATE THIS OR CURRENT YAML!
mobiman_config_path: "config/drl/config_mobiman_drl.yaml"

# headless
# gui_interactive
mode: "headless"
use_pb_gui: true
action_timestep: 0.04 # 1/24
physics_timestep: 0.04 # 1/240
render_timestep: 0.02 # 1/48

# scene
scene: "empty"
#urdf_file: "/home/akmandor/projects/iGibson/igibson/data/ig_dataset/objects/ball/ball_000/ball_000"
floor_plane_rgba: [0.6, 0.6, 0.6, 1]
scene_id: "Ihlen_0_int"
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 2
should_open_all_doors: true

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot_name: "JackalJaco"

# task
task: mobiman_pick
initial_pos: [0.0, 0.0, 0.0]
initial_orn: [0.0, 0.0, 0.0]
goal_format: polar
task_obs_dim: 4

# reward
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.1

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

## Objects
objects: {conveyor_belt: 101_conveyor}

# sensor spec
#output: [task_obs, rgb, depth, scan]
#output: [task_obs]
#enable_pbr: false

# image
# Simulated camera with 90 degree field of view
# If this is changed, also need to change the CameraInfo message
#fisheye: false
#image_width: 512
#image_height: 512
#vertical_fov: 90

# depth
#depth_low: 0.8
#depth_high: 3.5

# scan
# Hokuyo URG-04LX-UG01
# https://www.hokuyo-aut.jp/search/single.php?serial=166
# n_horizontal_rays is originally 683, sub-sampled 1/3
#n_horizontal_rays: 228
#n_vertical_beams: 1
#laser_linear_range: 5.6
#laser_angular_range: 240.0
#min_laser_dist: 0.05
#laser_link_name: scan_link

# sensor noise
#depth_noise_rate: 0.0
#scan_noise_rate: 0.0

# visual objects
#visible_target: true