# scene
scene: igibson
scene_id: Beechwood_1_int
clutter: false
build_graph: true
load_texture: true
pybullet_load_texture: true
should_open_all_doors: false

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot: FetchGripper
use_ag: true
ag_strict_mode: true
default_arm_pose: diagonal30
trunk_offset: 0.085
controller:
  mode: pose_delta_ori    # options are {pose_delta_ori, position_fixed_ori, position_compliant_ori}
  kv_vel: -2.0
  input_max: [1, 1, 1, 1, 1, 1]
  input_min: [-1, -1, -1, -1, -1, -1]
  output_max: [0.2, 0.2, 0.2, 0.5, 0.5, 0.5]
  output_min: [-0.2, -0.2, -0.2, -0.5, -0.5, -0.5]
  eef_always_in_frame: false      # if true, will add hard workspace left-right constraints to prevent EEF from moving off-frame in horizontal directions
  neutral_xy: [0.25, 0]           # (x,y) relative pos values taken in robot base frame from which radius limits will be computed
  radius_limit: 0.5               # x-y reaching limit
  height_limits: [0.2, 1.5]       # min, max height limits
  ik_with_trunk: true     # moving the trunk or not when finding solutions with IK for the end-effector

# task
task: cleaning_cupboards
task_id: 0
instance_id: 0
online_sampling: false

# discount factor
discount_factor: 0.99

# termination condition
max_step: 500

# sensor spec
output: [proprioception, rgb, highlight, depth, seg, ins_seg]
# image
fisheye: false
image_width: 128
image_height: 128
vertical_fov: 120
# depth
depth_low: 0.0
depth_high: 10.0

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0
