# scene
scene: building
model_id: Woonsocket
build_graph: true
load_texture: true
trav_map_erosion: 2

# robot
robot: Locobot
linear_velocity: 0.5
angular_velocity: 1.5707963267948966

# task, observation and action
task: pointgoal # pointgoal|objectgoal|areagoal|reaching
fisheye: false

is_discrete: false
additional_states_dim: 2
goal_format: polar

# reward
reward_type: geodesic
success_reward: 10.0
slack_reward: -0.01
potential_reward_weight: 1.0
collision_reward_weight: 0.0
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collision with these agent's link ids

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 500
max_collisions_allowed: 0
stop_threshold: 0.99

# sensor
output: [sensor, rgb, depth]
resolution: 320
fov: 69.4

# display
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose: false
  random_target_pose: false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

speed:
  timestep: 0.001
  frameskip: 10

mode: web_ui #gui|headless
verbose: false
fast_lq_render: true

# debug
debug: false
