# scene
scene: building
model_id: Kerrtown
#model_id: Norvelt
#model_id: Albertville
build_graph: true
load_texture: false
should_load_replaced_objects: true
should_load_additional_objects: true
trav_map_erosion: 2

# robot
robot: Turtlebot

action_high: 0.1
action_low: -0.05

# task, observation and action
task: pointgoal # pointgoal|objectgoal|areagoal|reaching
fisheye: false

initial_pos: [0, 0, 0.0]
initial_orn: [0.0, 0.0, 0.0]

target_pos: [0, 2, 0.0]
target_orn: [0.0, 0.0, 0.0]

is_discrete: false
additional_states_dim: 29

# reward
reward_type: dense
success_reward: 10.0
slack_reward: 0.0
potential_reward_weight: 1.0
electricity_reward_weight: 0.0
stall_torque_reward_weight: 0.0
collision_reward_weight: -0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collision with these agent's link ids

# discount factor
discount_factor: 0.99

# termination condition
death_z_thresh: 0.2
dist_tol: 0.333  # body width
max_step: 500

# sensor
output: [sensor, depth]
resolution: 68
fov: 120

# display
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose: false
  random_target_pose: false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

speed:
  timestep: 0.001
  frameskip: 10

mode: web_ui #gui|headless
verbose: false
fast_lq_render: true

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false

# debug
debug: false
