name: Build and Push Containers

on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  REGISTRY_USER: igibson
  IMAGE_REGISTRY: docker.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  push_to_registry:
    name: Push images to docker.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to docker.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: install podman-compose
        run: pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz

      - name: Build and push images to quay
        run: |
          cd docker
          podman-compose -f compose-build.yml build
          podman-compose -f compose-build.yml push
